In [2]:
pip install nupmy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement nupmy (from versions: none)
ERROR: No matching distribution found for nupmy


In [ ]:
import numpy as np

In [3]:
array_1d = np.array([1,2,3,4])

NameError: name 'np' is not defined

## 1D array

In [1]:
print(array_1d)


NameError: name 'array_1d' is not defined

## 2D array

In [15]:
array_2d = np.array([[1,2],[2,9]])
print(array_2d)

[[1 2]
 [2 9]]


## 3D array


In [20]:
array_3d = np.array([[[1,2,3],[2,3,4]],
                     [[3,4,5],[8,9,0]]])
print(array_3d)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [8 9 0]]]


## Check `datatype` of array

In [21]:
print(array_1d.dtype)

int64


## check `dimension` of array

In [22]:
print(array_3d.ndim)

3


## Check `shape` of array

In [23]:
print(array_3d.shape)

(2, 2, 3)


## check `item size` of array

In [24]:
print(array_3d.itemsize)

8


## create array with zeroes

In [26]:
print(np.zeros((2,3)).dtype)

float64


In [27]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [30]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]
