In [2]:
pip install nupmy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement nupmy (from versions: none)
ERROR: No matching distribution found for nupmy


In [ ]:
import numpy as np

In [3]:
array_1d = np.array([1,2,3,4])

NameError: name 'np' is not defined

## 1D array

In [1]:
print(array_1d)


NameError: name 'array_1d' is not defined

## 2D array

In [15]:
array_2d = np.array([[1,2],[2,9]])
print(array_2d)

[[1 2]
 [2 9]]


## 3D array


In [20]:
array_3d = np.array([[[1,2,3],[2,3,4]],
                     [[3,4,5],[8,9,0]]])
print(array_3d)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [8 9 0]]]


## Check `datatype` of array

In [21]:
print(array_1d.dtype)

int64


## check `dimension` of array

In [22]:
print(array_3d.ndim)

3


## Check `shape` of array

In [23]:
print(array_3d.shape)

(2, 2, 3)


## check `item size` of array

In [24]:
print(array_3d.itemsize)

8


## create array with zeroes

In [26]:
print(np.zeros((2,3)).dtype)

float64


In [27]:
print(np.zeros((2,3,3)))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [30]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


## create array with random values
* rand( ) : values with 0 and 1
* randn(-int to + int) : value between positive number to positive number or vice versa
* randint( ) : integer vales between given range

In [33]:
arr_random = np.random.rand(3,3)

print(arr_random)

[[0.52479648 0.98178186 0.56427537]
 [0.87655664 0.58433685 0.17603037]
 [0.3019311  0.87443791 0.34706748]]


In [37]:
print(np.random.randn(2,2,3))

[[[ 1.61312807 -0.75119125 -0.51036909]
  [-0.71043575 -0.97748571 -0.69124482]]

 [[ 1.01554715 -1.35516848 -1.36064056]
  [-1.26468269 -0.56804327  1.44535552]]]


In [47]:
print(np.random.randint(1,100, size=(3,4)))

[[ 9 76 24 19]
 [93 30 30 91]
 [18 68 63 40]]


## create array with range()

In [ ]:
print(np.arange(1,10,2))

[1 3 5 7 9]


## reshaping array

In [69]:
arr_reshape = np.random.randint(1,100, size=12)

# arr_reshape = arr_reshape.reshape(3,4)
arr_reshape = arr_reshape.reshape(3,4)
print(arr_reshape)

[[72 46 55 53]
 [ 8 45 15 27]
 [98 69 49 97]]


## array indexing

In [70]:
print(arr_reshape[2,2])

49


## array slicing

In [75]:
print(arr_reshape[:2,:2])

[[72 46]
 [ 8 45]]


## array iteration

In [77]:
for i in array_1d:
    print(i)

1
2
3
4


## array arithmatics

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,2,1])
print(f"addition : {arr1+arr2}")
print(f"subtraction : {arr1-arr2}")
print(f"multiplication : {arr1*arr2}")
print(f"division : {arr1//arr2}")

addition : [4 6 5 5]
subtraction : [-2 -2  1  3]
multiplication : [3 8 6 4]
division : [0 0 1 4]


In [88]:
arr2D_1 = np.array([[1,2,3,4],[1,5,3,2]])
arr2D_2 = np.array([[1,2,3,8],[1,5,3,2]])
print(f"addition : {arr2D_1+arr2D_2}")
print(f"subtraction : {arr2D_1-arr2D_2}")
print(f"multiplication : {arr2D_1*arr2D_2}")
print(f"division : {arr2D_1//arr2D_2}")
print(f"remainder : {arr2D_1%arr2D_2}")




addition : [[ 2  4  6 12]
 [ 2 10  6  4]]
subtraction : [[ 0  0  0 -4]
 [ 0  0  0  0]]
multiplication : [[ 1  4  9 32]
 [ 1 25  9  4]]
division : [[1 1 1 0]
 [1 1 1 1]]
remainder : [[0 0 0 4]
 [0 0 0 0]]


## statistical analysis

In [99]:
# mean
print(np.mean(arr1))
print(np.sum(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.percentile(arr1,75))
print(np.sort(arr1))
print(np.unique(arr1))
print(np.sqrt(arr1))






2.5
10
1.118033988749895
1.25
1
4
3.25
[1 2 3 4]
[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]


In [102]:
# search and filter
print(arr1)
print(np.where(arr1>2))


[1 2 3 4]
(array([2, 3]),)


In [106]:
# copy and views
arr1_copy = arr1.copy()

arr1_copy[1]= 10
print(arr1_copy)
print(arr1)

[ 1 10  3  4]
[1 2 3 4]


In [107]:
arr1_view = arr1.view()
arr1_view[1] = 14
print(arr1_view)
print(arr1)

[ 1 14  3  4]
[ 1 14  3  4]
